apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: robotics-ingress

spec:
  tls:
    - hosts:
        - robotics.local
      secretName: robotics-tls

  rules:
    - host: robotics.local

      http:
        paths:
          - path: /
            pathType: Prefix

            backend:
              service:
                name: robotics-service

                port:
                  number: 80